=== which-biscuits/myCode/JavaDemo/out/production/Demo13/Question02.dtd
<!--1)	根元素是contactList，contactList中包含1~n个contact子元素，contact子元素包含name,gender,phone,qq,email元素，这个元素必须依次出现，并且元素中都可以包含文本元素(#PCDATA)-->
<!--2)	其中contact有id属性，必须，并且不能重复，不能以数字开头-->
<!--3)	contact有一个可选的属性vip，取值是true或false-->
<!--4)	按此DTD约束创建XML文件，并添加3条contact记录。注：括号前要有空格-->
<!ELEMENT contactList (contact+)>
<!ELEMENT contact (name, gender, phone, qq, email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT qq (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ATTLIST contact
        id ID #REQUIRED
        vip (true|false) #IMPLIED>

=== which-biscuits/myCode/javaDemo/Demo13/src/Question02.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE contactList SYSTEM "Question02.dtd">
<contactList>
    <contact id="test1">
        <name>王子潇</name>
        <gender>男</gender>
        <phone>1831231</phone>
        <qq>1231434353</qq>
        <email>123123@qq.com</email>
    </contact>
    <contact id="test2">
        <name>123455456</name>
        <gender>男</gender>
        <phone>12390854</phone>
        <qq>809709@qq.com</qq>
        <email>12312312</email>
    </contact>
</contactList>
